### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by NathanRSmith** [NathanRSmith/graphql-visualizer#2]

**Comment by sheerun** [comment]
So I basically stolen your code and created CLI version at https://github.com/sheerun/graphqlviz

I've added you to the credits and collaborators, but I could transfer the repo if you want.

**Comment by NathanRSmith** [comment]
Yeah, I noticed, ha. Do you think it would make more sense to consolidate the two, or make graphviz the cli/lib and graphql-visualizer just a webapp version that uses the lib? There's not much to be called a "lib", but I can imagine a variety of other views that illustrate other aspects of a graphql API.

**Comment by sheerun** [comment]
Well, I think cli / lib should be separate from webapp. You could use webpack / rollup on web version.

**Comment by NathanRSmith** [comment]
Sure, let's do that then. Your repo seems to have a bit of a following already, so I'm fine with keeping it there if I'm in the team list and able to contribute.
