### ISSUE TITLE
A lot of fields with type null

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [NathanRSmith/graphql-visualizer#4]
Hello,

I tried this tool on my schema (I can't share it because I'm under a NDA). And a lot of fields have null type.

I know you can't tell much without the schema itself. but if you have any idea on how to fix it I would be happy.

If there is really nothing you can do I will try to obfuscate it and ask if it breaks my NDA.

Best regards

**Comment by NathanRSmith** [comment]
if you could create a single entity with dummy fields that illustrates the null issue that would be very helpful.

**Comment by yurigenin** [comment]
Anything type of LIST (i.e. [Customer!]! ) will have null. Basically, if you use a LIST with non-nullable combinations you will get nulls: [Customer!] or [Customer]! or [Customer!]!

**Comment by NathanRSmith** [comment]
I am able to reproduce. Will fix in https://github.com/sheerun/graphqlviz/issues/7

**Comment by NathanRSmith** [comment]
Sorry, for some reason I thought this was the same as the other repo. I will re-close when fixed.

**Comment by NathanRSmith** [comment]
Fixed in 7bc3187
